### ISSUE TITLE
app crash when try to download a movie

### ISSUE THREAD

**Issue by kr-nahid** [Tiarait/KinoTor#3]
#### Expected behavior
user should be able to download smoothly when they click on download icon and choose file format without crash . 

#### Actual behavior
when i click on download a video file app crash and restart the app

#### How to reproduce
* download the app
* open it
* click on a movie from list
* then scroll on видео (video)
* then click on download icon and choose file format and click format
* note the bug

> Browser/App version: KinoTor 0.41 
 Operating system: android 6.0

#### Recording Of The Bug
https://www.youtube.com/watch?v=36cisn6Sq6M

**Comment by Tiarait** [comment]
Thanks, I will correct this in the next version.
